#!/bin/sh
# ############################################
# Author: SkapiN <skapinthefourb@gmail.com>
# Date: October 2013
#
# Create two pseudo-terminal to
# simulate serial port for ICP.
# 
##############################################


/usr/bin/socat -d -d pty,link=/dev/ttyDEAMONPOLY,raw,echo=0,mode=0666 pty,link=/dev/ttyPOLY,raw,echo=0,mode=0666 &

while :
do
    /usr/bin/socat -d -d pty,link=/dev/ttyDEAMONPRINTER,raw,echo=0,mode=0666 TCP-LISTEN:6843
done
#kill -STOP "$$";