#!/bin/sh
# ############################################
# Author: SkapiN <skapinthefourb@gmail.com>
# Date: October 2013
#
# Create two pseudo-terminal to
# simulate serial port for ICP.
# 
##############################################
 /usr/bin/socat -d -d pty,link=/dev/ttyVIRT0,raw,echo=0 pty,link=/dev/ttyVIRT1,raw,echo=0 &

 /usr/bin/socat -d -d pty,link=/dev/ttyVIRT2,raw,echo=0 pty,link=/dev/ttyVIRT3,raw,echo=0 &


kill -STOP "$$";